services:
  traefik:
    image: traefik:v3.0
    container_name: gestar_traefik
    restart: unless-stopped
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "8000:8000"
      - "8888:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik-dynamic.yml:/etc/traefik/dynamic.yml:ro
    networks:
      - gestar_network

  db:
    image: mysql:8.0
    container_name: gestar_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./data/mysql:/var/lib/mysql # Bind mount pour voir les fichiers sur ton PC
    networks:
      - gestar_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: gestar_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - gestar_network

  backend:
    build: ./backend
    container_name: gestar_api
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
      - elasticsearch
    networks:
      - gestar_network

  frontend:
    build: ./frontend
    container_name: gestar_web
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://api.localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - gestar_network

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: gestar_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: gestar_db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - gestar_network
    depends_on:
      - db

# Volumes nommés pour que Docker garde tes données sur le disque dur
volumes:
  mysql_data:
  es_data:

networks:
  gestar_network:
    driver: bridge