# Alembic Configuration File
# This file contains the configuration settings for Alembic
# For Alembic documentation and user guide see:
# https://alembic.sqlalchemy.org

[alembic]
# path to migration scripts
script_location = alembic

# template_location =

# sys_path =
# defines a list of files that contains Python packages, that must be on the
# current working directory's path in order to use 'import' statements
# to access and load the modules within the version .py files.
#
# By default, this is ``as is``, what means the current working directory is
# used. set the following to 1 to prepend the current working directory to the
# path before importing the file containing the migration version
#prepend_sys_path = 1

# timezone to use when rendering the date within the migration file
# as well as the filename.
# String value is passed to the `timestamp()` method of python's datetime.datetime object.
# Leave blank for migrating without timestamps
#sqlalchemy.url = driver://user:password@localhost/dbname

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
